### ISSUE TITLE
A bug in ParEGO algorithm

### ISSUE THREAD

**Issue by zhandawei** [BIMK/PlatEMO#11]
**Describe the bug**
In the ParEGO algorithm, the selected updating point should have the highest EI value, but has the lowest EI value in current implementation.

**original code**
EvolALG.m file, Line 29 : `[~,index] = sort(EI,'descend');`

**corrected code**
EvolALG.m file, Line 29 : `[~,index] = sort(EI,'ascend');`

**The performance of ParEGO improves significantly after the correction.**

**Comment by anonymone** [comment]
Hi @zhandawei , Thanks for your bug report.  now bug 🐛 has been fixed. ❤️
