### ISSUE TITLE
The normalize function should not be newly defined.

### ISSUE THREAD

**Issue by tomtkg** [BIMK/PlatEMO#117]
Matlab has normalize function.
https://www.mathworks.com/help/matlab/ref/double.normalize.html

This file causes some problems.
https://github.com/BIMK/PlatEMO/blob/master/PlatEMO/Algorithms/Multi-objective%20optimization/CLIA/normalize.m

[This line](https://github.com/BIMK/PlatEMO/blob/master/PlatEMO/Algorithms/Multi-objective%20optimization/MOEA-D-UR/MOEADUR.m#L79) uses `X = normalize(X,'norm');`
[This line](https://github.com/BIMK/PlatEMO//blob/master/PlatEMO/Algorithms/Multi-objective%20optimization/MOEA-D-DCWV/updateWeight.m#L17) uses `objs = normalize(objs,'range');`

**Comment by DestinyMy** [comment]
Thank you for your advice. We'll test it as soon as possible.

**Comment by DestinyMy** [comment]
The algorithm uses its own normalization method that is different from the methods provided by MATLAB, hence we retain the function even if it may cause problems in some cases.

**Comment by DestinyMy** [comment]
Thanks for your advice, we'll rename it in the next update.
