### ISSUE TITLE
Bring back the supervised multi-objective optimization algorithm.

### ISSUE THREAD

**Issue by tomtkg** [BIMK/PlatEMO#118]
The supervised multi-objective optimization algorithm (SMOA) merged in [this pull request](https://github.com/BIMK/PlatEMO/pull/114) has been removed.
The paper is available [here](https://ieeexplore.ieee.org/document/9870375).

I think SMOA will work with PlatEMO 4.0 by changing the following four lines.

- loadData.m (line 1): function Population = loadData(Problem)
- loadData.m (line 22): Population = Problem.Evaluation(Dec);
- SMOA.m (line 44): Population = loadData(Problem);
- SMOA.m (line 66): Population = [Population,Problem.Evaluation(decs)];

**Comment by DestinyMy** [comment]
Thank you for your advice. We'll test it as soon as possible.

**Comment by tomtkg** [comment]
Thank you! :D
