### ISSUE TITLE
Question about function evaluation

### ISSUE THREAD

**Issue by mich0611** [BIMK/PlatEMO#119]
It's really an excellent platform for MOP, full of various algorithms and benchmark problems.
Just a question about "function evaluations" in the environment setting. 
How do we count the number of function evaluations in one run of MOEA ?
Is it equal to [gen_number * populaiton size * objective number] ?
Thanks !

**Comment by tomtkg** [comment]
The PROBLEM class has [FE property](https://github.com/BIMK/PlatEMO/blob/master/PlatEMO/Problems/PROBLEM.m#L12). 
FE property is number of consumed function evaluations.

On [line 154](https://github.com/BIMK/PlatEMO/blob/master/PlatEMO/Problems/PROBLEM.m#L154), FE is updated in the Evaluation function. That is, we count the number of function evaluations.
The Evaluation function is often called from operator.
Ex)[OperatorGA line 73](https://github.com/BIMK/PlatEMO/blob/master/PlatEMO/Algorithms/Utility%20functions/OperatorGA.m#L73).

**Comment by tomtkg** [comment]
FE is independent of the objective number.
FE may be equal to [gen_number * populaiton size].
For NSGA-II, FE is equal to [gen_number * populaiton size] if `populaiton size is even`.
FE is not equal to [gen_number * populaiton size] if `populaiton size is odd`.

**Comment by mich0611** [comment]
Okay, I got it. Thanks for your reply :)
