### ISSUE TITLE
what is the usage of  function 'PF'

### ISSUE THREAD

**Issue by amen183** [BIMK/PlatEMO#25]
what is the usage of  function 'PF'? where is it invoked?

**Comment by anonymone** [comment]
@amen183  PF function is used to sample reference points on Pareto front.  It is invoked in https://github.com/BIMK/PlatEMO/blob/352bc17bba3f00676314393b3b8895e9687933b2/PlatEMO/Public/GLOBAL.m#L117

**Comment by amen183** [comment]
Thanks for your response. Now, I have another question. If there is coupling between variables, how should I change the codes? (I use the algrithom 'NSGAII')

**Comment by anonymone** [comment]
@amen183 Hi, All variables are coupling.So you do not change any code of PlatEMO.

**Comment by anonymone** [comment]
I will close this issue, but it's still available for discussion.
