### ISSUE TITLE
problems definition is wrong

### ISSUE THREAD

**Issue by Claymoreterasa** [BIMK/PlatEMO#30]
when i make experiments on zdt problem, i found zdt1,2,3,4,6 is  definited wrongly, but don't know if other problem is also wrong

from https://sop.tik.ee.ethz.ch/download/supplementary/testproblems/zdt1/index.php
In zdt1
false
`        function PopObj = CalObj(obj,PopDec)  
            PopObj(:,1) = PopDec(:,1);  
            g = 1 + 9 * sum(PopDec(:,2:end),2);  
            h = 1 - (PopObj(:,1)./g).^0.5;  
            PopObj(:,2) = g.*h;  
        end
`

true
`        function PopObj = CalObj(obj,PopDec)  
            PopObj(:,1) = PopDec(:,1);  
            g = 1 + 9 / (size(PopDec,2)-1) * sum(PopDec(:,2:end),2);  
            h = 1 - (PopObj(:,1)./g).^0.5;  
            PopObj(:,2) = g.*h;  
        end  
`

**Comment by anonymone** [comment]
hi! @Claymoreterasa , Thanks for your issue. It is not a wrong definition of ZDT due to the case that ZDT problems be defined differently in different papers. And the ZDT in PlatEMO is one of them.

**Comment by Claymoreterasa** [comment]
sry :)
