### ISSUE TITLE
DAS-CMOPs

### ISSUE THREAD

**Issue by ArthurFarah** [BIMK/PlatEMO#33]
Hi, 

I'm looking for the DAS-CMOPs (Difficulty Adjustable and Scalable Constrained Multi-objective Test Problems) toolkit implementation (https://arxiv.org/abs/1612.07603).

While there are many benchmarking of multi and many objective problems, there are few options for working with many constraint problems. So, including these problems in PlatEMO would be a good contribution to cover this gap in the framwork.

I take this opportunity to thank all the project staff!

Thank you in advance.

Arthur,

**Comment by anonymone** [comment]
Hi @ArthurFarah ,Thanks for your advice!
We have been focusing on the constraint problems and trying to add some algorithms into PlatEMO. We will add the problems you mentioned in the future version.
