### ISSUE TITLE
I CAN'T RUN NSGA-III ,BUT NSGA-II IS OK.

### ISSUE THREAD

**Issue by junewgl** [BIMK/PlatEMO#35]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45283002/57579721-a6172680-74d2-11e9-891a-20d8df0ef0d3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]windows 

**Smartphone (please complete the following information):**

**Additional context**
MATLAB 2019

**Comment by junewgl** [comment]
问题已解决。

**Comment by anonymone** [comment]
Good.
