### ISSUE TITLE
I cannot browse algorithms and problems 

### ISSUE THREAD

**Issue by foufa89** [BIMK/PlatEMO#36]
Hi, 

I'm trying to choose other problems or algorithms but the slider doesn't work
I can choose one of the shown ones only

![image](https://user-images.githubusercontent.com/45772169/57717705-17dea400-767c-11e9-903f-b7dd3498e185.png)

Matlab version : (2018a)
OS: Windows

**Comment by anonymone** [comment]
You need to add your own peoblems or algorithms according to the rules of PlatEMO.

取得 Outlook<https://aka.ms/ghei36>

寄件者: foufa89
寄件日期: 5月15日 星期三 01:18
主旨: [BIMK/PlatEMO] I cannot browse algorithms and problems  (#36)
收件者: BIMK/PlatEMO
副本: Subscribed


Hi,
I'm trying to choose other problems or algorithms but the slider doesn't work
I can choose one of the shown ones only
Matlab version : (2018a)
OS: Windows

**Comment by foufa89** [comment]
Hi @anonymone,
Thanks for your prompt reply, 
I mean that I cannot select one of the existing algorithms(/problems) in PlatEMO, dMOPSO for example.
The action down of the slider doesn't respond.

**Comment by anonymone** [comment]
@foufa89 Do you use mouse? PlatEMO is not support touch pad well.
