### ISSUE TITLE
i didn't find EMOCA Algorithm (An Evolutionary Multi-Objective Crowding Algorithm) 

### ISSUE THREAD

**Issue by pmramy** [BIMK/PlatEMO#39]
Dears , i'm trying to compare result for different algorithms EMOCA vs NSGA ll , and i did not find EMOCA algorithm included , i attached the original paper for EMOCA algorithm so could anyone describe to me if is included under another name ?? or what !!

[An Evolutionary Multi-Objective Crowding Algorithm (EMOCA).pdf](https://github.com/BIMK/PlatEMO/files/3416997/An.Evolutionary.Multi-Objective.Crowding.Algorithm.EMOCA.pdf)

**Comment by anonymone** [comment]
hi @pmramy! Unfortunately, EMOCA  does not include in PlatEMO. But you still can write it following our manual.
