### ISSUE TITLE
MOEAD有严重BUG。

### ISSUE THREAD

**Issue by gongyongq** [BIMK/PlatEMO#40]
下载最新版platemo，MOEAD在很多问题的求解上都出现问题。例如下图，求解C3-DTLZ4，一个解都没有搜索到。试过jMetal、pymoo、deap等都是能收敛的，因此认为这是一个比较严重的BUG。希望尽快给出答复。谢谢！
![image](https://user-images.githubusercontent.com/53175954/61988830-713e5880-b059-11e9-9ff9-5eba71c3a484.png)

**Comment by anonymone** [comment]
你好，@gongyongq 
你提出的问题，我们已经了解了。但是这个并不是什么严重的BUG，甚至，本来就该如此。
MOEA/D __原版__ 并没有任何约束处理机制，故它无法求解带约束的问题。
如果你还有疑问，可以参考一下MOEA/D的论文。谢谢！

**Comment by anonymone** [comment]
如果没什么其他问题，我就关了。

**Comment by gongyongq** [comment]
> 如果没什么其他问题，我就关了。

非常感谢您的指点！我回头认真研究一番。这两天出去玩了没有留意到。。

**Comment by gogocen** [comment]
您好，想请问一下MOEAD算法是无法处理有约束的多目标问题吗
