### ISSUE TITLE
Error in IMMOEA_F*

### ISSUE THREAD

**Issue by EvaFlower** [BIMK/PlatEMO#41]
**Describe the bug**
Implementation of constraint function g in IMMOEA_F* is wrong

**To Reproduce**
For example, in IMMOEA_F1.m:
https://github.com/BIMK/PlatEMO/blob/b7be97a7a49dbeb1f799e101e84dd45935a56de3/PlatEMO/Problems/MOPs%20in%20IM-MOEA/IMMOEA_F1.m#L32-33
      t = (1+5*repmat(2:D,size(X,1),1)/D).*X(:,2:D) - repmat(X(:,1),1,D-1);
      g = 1 + 9*mean(t.^2,2);

**Expected behavior**
t should be ((1+5)*repmat...) 
according to the paper:
A Multiobjective Evolutionary Algorithm using Gaussian Process-based Inverse Modeling

**Comment by anonymone** [comment]
Hi, @EvaFlower, I have checked the problems. And I confirm it is not an issue.
Here is my reason:
In the recent code,  the `repmat(2:D,size(X,1),1)/D` equals to `Sum(i/n)` in original paper. and alpha was set as 5. But in your code, we miss`1+` .
