### ISSUE TITLE
How to add problems linking with other MATLAB files?

### ISSUE THREAD

**Issue by dzhmaple** [BIMK/PlatEMO#45]
**Is your feature request related to a problem? Please describe.**
I want to add a problem having external inputs besides the global ones. And I have done some work previously, but it did not work. Therefore, I want some help, or could you please give me an example?

**Describe the solution you'd like**
My aim is to integrate the optimization into other MATLAB codes, and some known parameters should be delivered to the problem to implement the optimization.

**Describe alternatives you've considered**
I know the combinatorial MOPs have some parameters which should be read before the optimization, but it may cost much time to save and load the data to obtain the wanted results. Therefore, I want to define those external parameters in other m file. The definitions I have done a re follows:

This is a classdef function to define and get the parameters:
```
classdef REParameters < handle  
    properties(SetAccess = private)
        Pb; 
        cjgl;   
        T;  
        C;  
        singlepaths;   
        V; 
        Pes;    
        RLES;   
    end
    
    methods
        function obj = GetObj(obj)
            
            persistent ReParameters;
            if nargin > 0
                ReParameters = obj;
            else
                obj = ReParameters;
            end
        end
    end
end
```

To integrate these parameters into the problem, I modified the PROBLEM.m file as follows:
```
    properties(SetAccess = private)
        Global; % The current GLOBAL object
        ReParameters;
    end
    methods(Access = protected)
        %% Constructor
        function obj = PROBLEM()
            obj.Global = GLOBAL.GetObj();
            obj.ReParameters = PEParameters.GetObj();
        end
        ...
```

However, it did not work with errors (No static function GetObj exists in REParameters). Could you help me to improve the work?

**Comment by anonymone** [comment]
@dzhmaple hi, to solve this error, you need to define your method as a static method. please, kindly check this page [https://www.mathworks.com/help/matlab/matlab_oop/static-methods.html](https://www.mathworks.com/help/matlab/matlab_oop/static-methods.html)

**Comment by anonymone** [comment]
seem the problem has solved. Closed, but it still can discuss.
