### ISSUE TITLE
Can I get the original code of all the algorithms in platemo? This is very important to me, thank you!

### ISSUE THREAD

**Issue by daydayupgogo** [BIMK/PlatEMO#46]
I read your paper about PlatEMO, PlatEMO is very useful. But I want to learn some specific algorithms, such as NSGA-2. These original codes can help me understand the idea of the algorithm.I really need the original code, thank you very much!

**Comment by lfarizav** [comment]
Hi,

I would recommend to see Deb's code.

http://www.iitk.ac.in/kangal/codes/nsga2/nsga2-gnuplot-v1.1.6.tar.gz

Best regards,

Felipe

**Comment by daydayupgogo** [comment]
thank you

**Comment by anonymone** [comment]
It seems that the issue is solved. Are there other problems asking for discussing? @daydayupgogo
