### ISSUE TITLE
Using DTLZ3 problem and HV as metric, it always results 0 using the current version of PlatEMO

### ISSUE THREAD

**Issue by Arakkun** [BIMK/PlatEMO#53]
I tried making a sensitivity analysis of NSGAIII and MOEAD using PlatEMO, and the HV rarely results more than 0, if using the DTLZ3 problem.

This didn't happen using the previous version of the Hypervolume calculation. 

In case I can try giving the dumps of the GLOBAL variable if needed ( I have a few hundred of those )

**Comment by anonymone** [comment]
@Arakkun The key reason may root in the fact that the NSGAIII and the MOEA/D have a not good performance.  So, It would be better to increase evaluation times.

**Comment by fariaslrc** [comment]
It is the same with me, the NSGA-III does not converge on the DTLZ3, other MOEAs converge, for example, AR-MOEA.

In the WFG3 problem with ten objectives, the HV is zeroing out. When trying to replicate the paper, "An evolutionary algorithm with multiple objectives and based on indicators with adaptation of the reference point for better versatility." The HV results using AR-MOEA, RVEA, MOEA / DD, and NSGA-III with ten objectives are zero too, this is repeated in WFG3 with twelve and fifteen objectives.
