### ISSUE TITLE
Can not add custom algorithm in the GUI

### ISSUE THREAD

**Issue by borisdjartov** [BIMK/PlatEMO#55]
So i want to use PlatEMO for research and i am trying to add a custom algorithm based on NSGAII.  I created a new folder (Boris) and copy pasted the contents of NSGAII into it. I also changed the name of the main file from NSGAII to Boris. I then tried to use it with the GUI but it is not in the list of algorithms.I can however run it outside the GUI by using the main method. How can i add this algorithm so it shows up in the GUI?

Thank you for your time.

**Comment by anonymone** [comment]
@borisdjartov Hi, You can kindly check out the manual of PlatEMO. In the fourth part, we introduced the way to add custom algorithms.  You can find the manual in the ./PlatEMO/.
