### ISSUE TITLE
Question: How to add new problems with GUI?

### ISSUE THREAD

**Issue by ramonple** [BIMK/PlatEMO#56]
I would like to use PlatEMO for my own problem. I put my problem m.file in the Problems folder, but I cannot find it in the problem list in GUI.

Below is a simple example:
<img width="652" alt="test" src="https://user-images.githubusercontent.com/64589946/80706451-47322f00-8ae0-11ea-9a56-9395c0155d9a.png">

Could anyone tell me where the problems are?

**Comment by anonymone** [comment]
@ramonple you have a similar issue with #55 , pls check out the answer.

**Comment by anonymone** [comment]
Similar issue with #55, Closed but it is still available for discussion.
