### ISSUE TITLE
Variation of average metric value bug

### ISSUE THREAD

**Issue by Cosijopiii** [BIMK/PlatEMO#63]
In the experiment module, the option **variation of average metric** doesn't give us a chart only shows a point; in the test module, this option shows a chart with the variation in terms of function evaluations. is this a bug?  

thanks for reading me.

![image](https://user-images.githubusercontent.com/7028517/87419024-5d587300-c598-11ea-8253-2ba26144f7dd.png)

**Comment by DestinyMy** [comment]
Hello, this is not a bug. The loss of other points since there is no feasible solution at those numbers of evaluations, and the metric values are unavailable.
