### ISSUE TITLE
No metrics running withou GUI

### ISSUE THREAD

**Issue by paulojunqueira** [BIMK/PlatEMO#70]
Hi, I am having some issues while running experiments with PlatEMO without GUI. After finishing running it only returns the values: metric and result, but metric contains only runtime.
Is there a way to specify the metric without GUI?

Thanks in advance.

**Comment by DestinyMy** [comment]
Hello, sorry about that, this function is not provided yet, you need to calculate it manually.

**Comment by paulojunqueira** [comment]
That is Ok, thank you.
