### ISSUE TITLE
Error using PlatEMO with GUI

### ISSUE THREAD

**Issue by mluque72** [BIMK/PlatEMO#82]
When I execute PlatEMO with GUI using the new version, I always obtain the following message:
"The algorithm terminates unexpectedly, please refer to the command windows for details"

Can anyone help me?

Thank you very much in advance.

**Comment by DestinyMy** [comment]
Hello, it's very likly your code was written wrong. GUI is just used to run algorithm, it will catch all errors to ensure GUI don't crash.
